"""empty message

Revision ID: 2e9fc3ee4e59
Revises: 18a75a4bc424
Create Date: 2023-09-07 04:08:12.989183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e9fc3ee4e59'
down_revision = '18a75a4bc424'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_participate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_key', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_participate', schema=None) as batch_op:
        batch_op.drop_column('team_key')

    # ### end Alembic commands ###
