"""empty message

Revision ID: 7de997ac9f0b
Revises: 2e9fc3ee4e59
Create Date: 2023-09-07 19:38:14.761951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7de997ac9f0b'
down_revision = '2e9fc3ee4e59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('winers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marks', sa.Integer(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('event_name')
        batch_op.drop_column('winers')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('winers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('winers', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('event_name', sa.VARCHAR(length=100), nullable=False))
        batch_op.create_foreign_key(None, 'event', ['event_name'], ['event_name'])
        batch_op.drop_column('marks')

    # ### end Alembic commands ###
