"""empty message

Revision ID: be3f2c3e490b
Revises: 09bbc723a1e0
Create Date: 2023-09-08 02:55:53.727198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be3f2c3e490b'
down_revision = '09bbc723a1e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('winers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_name', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('winers', schema=None) as batch_op:
        batch_op.drop_column('event_name')

    # ### end Alembic commands ###
