"""empty message

Revision ID: e66b3916d43d
Revises: da2dfc18c41c
Create Date: 2023-09-08 02:16:04.947466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e66b3916d43d'
down_revision = 'da2dfc18c41c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_participate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_leader', sa.String(), nullable=False))

    with op.batch_alter_table('winers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('marks', sa.Integer(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'team_participate', ['team_name'], ['team_name'])
        batch_op.drop_column('event_name')
        batch_op.drop_column('winers')
        batch_op.drop_column('team')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('winers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('winers', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('event_name', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'event', ['event_name'], ['event_name'])
        batch_op.create_foreign_key(None, 'team_participate', ['team'], ['team_name'])
        batch_op.drop_column('marks')
        batch_op.drop_column('team_name')

    with op.batch_alter_table('team_participate', schema=None) as batch_op:
        batch_op.drop_column('team_leader')

    # ### end Alembic commands ###
